Storeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('userapp',include('UserApp.urls')),
    path('cartapp',include('cart.urls')),
    path('products',include('products.urls')),
    path('search/',include('searchapp.urls')),
    # path('payment/',include('payment.urls')),
    path('payments/', include('payment.urls')),
    
]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UserApp/urls.py
from django.urls import path
from .import views

app_name='User'
urlpatterns = [
   
    path('user/',views.register,name='Register'),
    path('login/',views.login,name='Login'),
    path('logout/',views.logout,name='Logout'),
    path('useradderess/<int:id>',views.ADDUserAddress,name='useradderess'),
    path('addressform/<int:id>', views.AddressForm, name='addressform'),
    path('address/<int:id>', views.Address, name='address'),
    path('userdashboard/<int:id>',views.UserDashBoard,name='userdashboard'),
    path('us/',views.Us,name='us'),
    path('profilepage/<int:id>',views.Profiles,name='profilepage'),
    path('cart_page/',views.Carts,name='cart_page'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),

]
# url 'User:profile'

cart/urls.py
from django.urls import path
from .import views

app_name='Cart'
urlpatterns = [
   
    path('add_quantity/<int:id>',views.addcart,name='addcart'),
    path('cart_page/',views.cart_page,name='cart_page'),
    path('quantity_remove/<int:id>',views.quantity_remove,name='quantityremove'),
    path('removesingle/<int:id>',views.RemoveX,name='removeX'),
    path('Check_Out/', views.Checkout, name='checkout'),
    path('ClearAll/', views.ClearCart, name='clearall'),
]
# Cart:clearall




















# Cart:cartpage

mainapp/urls.py
from . import views
from django.urls import path

app_name='mainapp'
urlpatterns = [
    
    path('',views.Home,name='Home'),

]

products/urls.py
from django.urls import path
from . import views

app_name = 'Products'
urlpatterns = [
    path('products/',views.Products, name='products'),
    path('<slug:c_slug>/',views.Products,name='product_by_category'),
    path('details/<int:id>',views.Details, name='detail'),
]

#'Products:product'

searchapp/urls.py
from django.urls import path
from .import views

app_name='search'
urlpatterns = [
    path('search/',views.search,name='search'),
]
 

templates/nav_footer/footer.html
<div class="footer mt-4">
    <footer class="text-center text-lg-start text-white" style="background-color: #1c2331">

        <section class="d-flex justify-content-between p-4" style="background-color: #000000">

            <div class="me-5">
                <span>Get connected with us on social networks:</span>
            </div>

            <div>
                <a href="" class="text-white me-4">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="text-white me-4">
                    <i class="fab fa-github"></i>
                </a>
            </div>

        </section>

        <section class="">
            <div class="container text-center text-md-start mt-5">

                <div class="row mt-3">

                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

                        <h6 class="text-uppercase fw-bold">Company name</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #000000; height: 2px" />
                        <p>
                            OnePlus Mobiles
                        </p>
                    </div>

                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

                        <h6 class="text-uppercase fw-bold">Products</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #000000; height: 2px" />
                        <p>
                            <a href="#!" class="text-white">MDBootstrap</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">MDWordPress</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">BrandFlow</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Bootstrap Angular</a>
                        </p>
                    </div>

                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

                        <h6 class="text-uppercase fw-bold">Useful links</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #0b0b0e; height: 2px" />
                        <p>
                            <a href="#!" class="text-white">Your Account</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Become an Affiliate</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Shipping Rates</a>
                        </p>
                        <p>
                            <a href="#!" class="text-white">Help</a>
                        </p>
                    </div>



                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

                        <h6 class="text-uppercase fw-bold">Contact</h6>
                        <hr class="mb-4 mt-0 d-inline-block mx-auto"
                            style="width: 60px; background-color: #000000; height: 2px" />
                        <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
                        <p><i class="fas fa-envelope mr-3"></i> info@example.com</p>
                        <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
                        <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
                    </div>

                </div>

            </div>
        </section>

        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            Aromal Project
            <a class="text-white" href="#">OnePlus.in</a>
        </div>

    </footer>
</div>

templates/nav_footer/nav.html
{% load static %}
<nav class="navbar  navbar-expand-lg   sticky-top p-0 m-0 pb-1">
    <div class="container-fluid navbar_height py-2">
        <a class="navbar-brand pb-2 pt-0 ps-4 " href="{% url 'mainapp:Home'  %}">
            <svg viewBox="0.1 0.01 799.8099999999998 182.97" xmlns="http://www.w3.org/2000/svg" width="110" height="22">
                <g fill="#f50514">
                    <path
                        d="M88.56 28.51v17.47H17.14v119.99h120.71V94.71h17.05v88.27H.1V28.51zM154.9.01v28.5h28.56v17.47H154.9v28.5h-17.05v-28.5h-29.02V28.51h29.02V.01zM71.05 142.98V94.71H54.92V82.3h1.85c5.06 0 9.21-.92 11.98-3.22 2.76-2.3 4.6-6.43 4.6-11.49h15.21v75.39zM203.74 106.21c0-27.13 17.04-47.36 43.76-47.36 26.73 0 43.77 20.23 43.77 47.36 0 27.12-17.04 46.89-43.77 46.89-26.72 0-43.76-19.77-43.76-46.89zm68.64 0c0-17.93-8.29-32.19-24.88-32.19-16.58 0-25.34 14.26-25.34 32.19s8.3 32.18 25.34 32.18c17.05-.46 24.88-14.25 24.88-32.18zm34.56-45.52h18.89l30.4 50.57c2.77 5.06 6.45 12.88 6.45 12.88h.46s-.46-9.2-.46-15.64V60.69h17.97v90.57h-17.97l-31.33-50.11c-2.76-4.6-6.45-12.41-6.45-12.41h-.46s.46 9.65.46 15.63v46.89h-17.96zm93.98 0h66.81v15.17h-48.38v20.23h42.39v15.17h-42.39v24.37h48.84v15.63h-67.27zm125.32 0c10.6 0 18.43 3.22 23.96 8.28 5.06 5.05 8.29 12.41 8.29 20.69 0 17.01-11.52 28.5-30.41 28.5h-22.11v32.64h-18.89V60.69zm-21.19 42.76h18.89c9.67 0 14.74-5.52 14.74-13.33 0-8.28-5.53-13.34-14.28-13.34h-19.35zm66.34-42.76h18.43v74.94h42.38v15.63h-60.81zm70.95 0h18.43v61.61c0 9.19 4.61 16.09 17.05 16.09 11.51 0 17.04-6.9 17.04-16.09V60.69h18.43v61.61c0 19.3-11.98 30.8-35.01 30.8-23.96-.46-35.94-11.5-35.94-31.26zm101.82 62.53c1.38 11.03 7.37 15.17 20.27 15.17 9.21 0 17.51-3.22 17.51-11.5 0-8.73-8.76-10.57-22.58-13.79-16.12-3.68-31.33-7.81-31.33-26.66 0-17.93 14.75-27.13 34.56-27.13 20.27 0 33.63 10.12 35.01 28.05h-17.51c-.92-9.2-8.29-13.8-17.5-13.8-9.68 0-16.59 4.14-16.59 10.58 0 7.35 6.45 9.65 19.81 12.41 18.89 4.14 34.1 8.28 34.1 28.04 0 18.39-14.75 28.51-35.48 28.51-23.96 0-37.78-11.04-38.24-29.88z" />
                </g>
            </svg>
        </a>
        <button class="navbar-toggler  " type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse medium-background ps-2 navbar-collapse " id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">


                <a class="nav-link active" href="{% url 'Products:products' %}">All Products</a>
                {% for i in links %}
                <li class="nav-item">
                    <a class="nav-link active" href="{{i.get_url}}">{{ i.name }}</a>
                </li>
                {% endfor %}

                {% comment %} <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Tablet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Audio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">TV & Display</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Accessories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">Offers</a>
                </li> {% endcomment %}
            </ul>
            <div class="ms-auto p-2">
                <form class="d-flex" action="{% url 'search:search'  %}" role="search" method="GET">
                    <input class="form-control me-2 w-75 search_bar" type="search" name="q" placeholder="Search"
                        aria-label="Search">
                </form>
            </div>
            <div class="d-flex my-1">
                {% if user.is_authenticated %}
                {% comment %} <a href="{%  url 'User:profile' user.id %}" class="pt-2 px-2 text-decoration-none text-dark"><svg
                        xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                        <path
                            d="M480-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Zm80-80h480v-32q0-11-5.5-20T700-306q-54-27-109-40.5T480-360q-56 0-111 13.5T260-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T560-640q0-33-23.5-56.5T480-720q-33 0-56.5 23.5T400-640q0 33 23.5 56.5T480-560Zm0-80Zm0 400Z" />
                    </svg>{{user}}</a> {% endcomment %}
                    {% comment %} <a href="{%  url 'User:profiles' user.id %}" class="pt-2 px-2 text-decoration-none text-dark"><svg {% endcomment %}
                    <a href="{%  url 'User:profilepage' user.id %}" class="pt-2 px-2 text-decoration-none text-dark"><svg

                        xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                        <path
                            d="M480-480q-66 0-113-47t-47-113q0-66 47-113t113-47q66 0 113 47t47 113q0 66-47 113t-113 47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Zm80-80h480v-32q0-11-5.5-20T700-306q-54-27-109-40.5T480-360q-56 0-111 13.5T260-306q-9 5-14.5 14t-5.5 20v32Zm240-320q33 0 56.5-23.5T560-640q0-33-23.5-56.5T480-720q-33 0-56.5 23.5T400-640q0 33 23.5 56.5T480-560Zm0-80Zm0 400Z" />
                    </svg>profile</a>
                <a href="{% url 'User:Logout' %}" type="button" class="btn btn-outline-dark mx-1">logout</a>
                <a href="{% url 'Cart:cart_page' %}" type="button" class="btn bg-warning mx-1">Cart</a>
                {% comment %} {% url 'Cart:addcart details.id' %} {% endcomment %}
                {% else %}
                <a href="/admin/" type="button" class="btn   btn-outline-dark mx-1">Admin</a>
                <a href="{% url 'User:Login' %}" type="button" class="btn   btn-outline-dark mx-1">login</a>
                <a href="{% url 'User:Register' %}" type="button" class="btn  btn-outline-dark mx-1">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>















{% comment %} <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
            <a href="{% url 'User:Logout' %}" type="button" class="btn btn-primary mx-1">logout</a>
            <a href="{% url 'Cart:cartpage' %}" type="button" class="btn btn-primary mx-1">Cart</a>
            {% else %}
            <a href="{% url 'User:Login' %}" type="button" class="btn btn-primary mx-1">login</a>
            <a href="{% url 'User:Register' %}" type="button" class="btn btn-primary mx-1">register</a>
            {% endif %}

        </div>
    </div>
</nav> {% endcomment %}