Storeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('userapp',include('UserApp.urls')),
    path('cartapp',include('cart.urls')),
    path('products',include('products.urls')),
    path('search/',include('searchapp.urls')),
    # path('payment/',include('payment.urls')),
    path('payments/', include('payment.urls')),
    
]
if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UserApp/urls.py
from django.urls import path
from .import views

app_name='User'
urlpatterns = [
   
    path('user/',views.register,name='Register'),
    path('login/',views.login,name='Login'),
    path('logout/',views.logout,name='Logout'),
    path('useradderess/<int:id>',views.ADDUserAddress,name='useradderess'),
    path('addressform/<int:id>', views.AddressForm, name='addressform'),
    path('address/<int:id>', views.Address, name='address'),
    path('userdashboard/<int:id>',views.UserDashBoard,name='userdashboard'),
    path('us/',views.Us,name='us'),
    path('profilepage/<int:id>',views.Profiles,name='profilepage'),
    path('cart_page/',views.Carts,name='cart_page'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),

]
# url 'User:profile'

cart/urls.py
from django.urls import path
from .import views

app_name='Cart'
urlpatterns = [
   
    path('add_quantity/<int:id>',views.addcart,name='addcart'),
    path('cart_page/',views.cart_page,name='cart_page'),
    path('quantity_remove/<int:id>',views.quantity_remove,name='quantityremove'),
    path('removesingle/<int:id>',views.RemoveX,name='removeX'),
    path('Check_Out/', views.Checkout, name='checkout'),
    path('ClearAll/', views.ClearCart, name='clearall'),
]
# Cart:clearall




















# Cart:cartpage

mainapp/urls.py
from . import views
from django.urls import path

app_name='mainapp'
urlpatterns = [
    
    path('',views.Home,name='Home'),

]

products/urls.py
from django.urls import path
from . import views

app_name = 'Products'
urlpatterns = [
    path('products/',views.Products, name='products'),
    path('<slug:c_slug>/',views.Products,name='product_by_category'),
    path('details/<int:id>',views.Details, name='detail'),
]

#'Products:product'

cart/models.py
from django.db import models
from mainapp.models import Product


# Create your models here.
class Cart(models.Model):
    user=models.CharField(max_length=200)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)    
    quantity=models.IntegerField()
    class Meta:
        db_table='cart'
    def total(self):
        return self.quantity * self.product.price
class Order(models.Model):
    user=models.CharField(max_length=200)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()

products/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render,redirect
from mainapp.models import Product
from .models import *
from django.core.exceptions import ObjectDoesNotExist

def cart_page(req):
    cart = Cart.objects.filter(user=req.session['user'])  # Retrieve cart items\
    # Calculate grand total
    grand_total = sum(item.quantity * item.product.price for item in cart)
    return render(req, 'cart.html', {'cart': cart ,'grand_total': grand_total})


#add items to the cart and add quantity of the product
def addcart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)

    try:
        cart=Cart.objects.get(product=product,user=user)
        if cart.quantity<cart.product.stock:
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=product,quantity=1)
    return redirect('Cart:cart_page')



#remove the quantity of the product in cart using cart button (-) .
def quantity_remove(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    cart=Cart.objects.get(product=product,user=user)
    if cart.quantity>1:
        cart.quantity-=1
        cart.save()
    
    return redirect('Cart:cart_page')

# remove single product from the cart
def RemoveX(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    cart=Cart.objects.get(product=product,user=user)
    cart.delete()
    return redirect('Cart:cart_page')

def ClearCart(req):
    user = req.session['user']
    cart_items = Cart.objects.filter( user=user)
    for i in cart_items:
        i.delete()
    return redirect('mainapp:Home')


# def Checkout(req):
#     user=req.session['user']
#     cart_items = Cart.objects.filter( user=user )
   
#     for cart in cart_items:
#       products=Product.objects.get(id=cart.product.id)
#       try:
#         order=Order.objects.get(product=products,user=user)
#         if cart.quantity<cart.product.stock:
#             order.quantity+=cart.quantity
#             order.save()
            
#       except Order.DoesNotExist:
#            order=Order.objects.create(user=user,product=products,quantity=cart.quantity)
#       products.stock-=cart.quantity
#       products.save()
#       cart.delete()
#       return redirect('mainapp:Home')

def Checkout(req):
    user = req.session['user']
    cart_items = Cart.objects.filter(user=user)
        
    for cart in cart_items:
            products = Product.objects.get(id=cart.product.id)
            try:
                order = Order.objects.get(product=products, user=user)
                if cart.quantity < cart.product.stock:
                    order.quantity += cart.quantity
                    order.save()
            except Order.DoesNotExist:
                order = Order.objects.create(user=user, product=products, quantity=cart.quantity)
            products.stock -= cart.quantity
            products.save()
            cart.delete()
    return redirect('create_payment') 

products/views.py
from django.shortcuts import render, get_object_or_404,redirect
from mainapp.models import Product, Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage


def Details(req,id):
    detail=Product.objects.get(id=id)
    return render(req,"details.html",{'details':detail,})



def Products(req, c_slug=None, stock=None):
    c_page = None
    product_list = None
    if c_slug:
        c_page = get_object_or_404(Category, slug=c_slug)
        product_list = Product.objects.filter(category=c_page, available=True)
    else:
        product_list = Product.objects.filter(available=True)
    return render(req, "products.html", {'product': product_list, 'category': c_page})
    # paginator=Paginator(product_list,4)

    # try: 
    #     page=int(req.GET.get('page', '1')) 
    # except:
    #     page=1  
    # invalid page and empty page
    # try: 
    #     products=paginator.page(page) 
    # except( EmptyPage, InvalidPage): 
    #     products=paginator.page(paginator.num_pages)









templates/Userdashboard.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.87.0">
    <title>Dashboard Template · Bootstrap v5.1</title>
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="{% static '/css/profiles/profiles.css' %}" rel="stylesheet">
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'mainapp:Home'  %}">Open plus+</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3" href="#">Sign out</a>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url "User:profilepage" id=user.id %}">
                                <span data-feather="user"></span>
                                Profile
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url "User:us" %}">
                                <span data-feather="file"></span>
                                Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'User:cart_page' %}">
                                <span data-feather="shopping-cart"></span>
                                Cart
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="star"></span>
                                Wishlist
                            </a>
                        </li>
                        <li class="nav-item nav-link ">
                            <span data-feather="table"></span>
                            <a href="{% url "User:address" id=user.id %}" class="text-decoration-none text-dark">
                                <span>Address</span></a>
                            <a class="link-secondary addaddress " href="{% url "User:addressform" id=user.id %}"
                                aria-label="Add a new report">
                                <span data-feather="plus-circle"></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{% url 'mainapp:Home'  %}">
                                <span data-feather="corner-down-left"></span>
                                Back Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="log-out"></span>
                                Logout
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                {% block content %}

                {% endblock %}


            </main>
        </div>
    </div>

    .rowbx{
        margin-left:200px;
    }



    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <script src="https://unpkg.com/feather-icons"></script>
    <script src={% static "/js/index.js" %}></script>
</body>

</html>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OnePlus +</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="{% static 'css/product.css' %}">
    <link rel="stylesheet" href="{% static 'css/details.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    integrity="...">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
    {% include './nav_footer/nav.html' %}
    {% block content %}

    {% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

templates/cancel.html
<!DOCTYPE html>
<html>
<head>
    <title>Payment Canceled</title>
</head>
<body>
    <h1>Payment Canceled</h1>
    <p>Your payment has been canceled.</p>
</body>
</html>

templates/cart.html
{% extends "base.html" %}
{% block content %}
{% load custom_filters %}


<div class="main pt-4 cart_cart mx-2 mx-md-4 ">
    <div class="container-fluid cart_page">
        <div class="row cart_row ">
            <div class="col-12 m-0 w-100 p-0 pe-1 cart_col1">
                <div class="row rowax  bg-light mb-1 p-3  me-0 me-md-1">
                    <div class="col-10 pt-2 fs-5">From Saved Addresses</div>
                    <a href="{% url "Cart:clearall" %}" type="button" class="btn rounded-0 col cart_clear ms-1 fw-bolder">CLEAR
                        CART</a>
                </div>

            </div>
            {% comment %} cart product start here {% endcomment %}
            {% for i in cart %}
            <div class="row rowbx bg-light pb-2 mb-1 me-0 me-md-1 ">

                <div class="col-1">
                    <img class="img_back py-2 mt-1" src="{{i.product.image.url}}" height="180px"
                        alt="no img">
                </div>
                <div class="col-12 col-lg-4 detail_cart_p ms-lg-5  mt-lg-3  ps-lg-5 pt-3">
                    <p class="fw-bold">{{i.product.name}}</p>
                    <p class="fw-normal">Brand : Oneplus</p>
                    <p class="fw-normal">{{i.product.detail}}</p>
                    
                    <span >Total Amount :<span class="fw-bold"> ₹ {{i.total|add_commas }}</span></span>

                </div>
                <div class="col-5 rowbaa d-flex justify-content-center align-items-center">
                    <div class="row">
                        <a href="{% url 'Cart:quantityremove' i.product.id %}" type="button"
                            class="col-2 btn text-dark fw-bold btn-circle btn-outline-secondary me-2 btn-md ">-</a>
                        <input class="col-2 quantity text-center mt-1 " disabled value="{{i.quantity}}" max="8" name="" id="">
                        <a href="{% url 'Cart:addcart' i.product.id %}" type="button"
                            class="col-2 btn text-dark fw-bold btn-circle btn-outline-secondary  btn-md ms-3">+</a>


                    </div>
                </div>
                <a href="{% url 'Cart:removeX' i.product.id %}"  type="button"
                    class="col-12 rounded-circle text-decoration-none   removeX col-sm-1 ms-1 mt-auto mb-auto fs-4  d-flex justify-content-center align-items-center text-danger  rounded-0">X</a>
            </div>
            {% comment %} cart product end here  {% endcomment %}
            {% endfor %}
        </div>



        <div class="container-fluid pt-5 mt-5">
            <div class="row rowex bg-light mb-1 p-2  d-flex justify-content-end fixed-bottom z-index-3">
                <div class="col-3 fs-4 d-flex justify-content-center align-items-center">Grand Total:₹ {{grand_total|add_commas}}
                </div>
                <a href="{% url 'Cart:checkout' %}" type="button" class="col-4 btn rounded-0 checkout ms-1 me-5 p-4 fw-bolder mt-md-0 mt-2">CHECK
                    OUT</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/details.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="row ">
    <div class="col-12 col-lg-6 cart_col1 ms-5 ps-5">

        <img src="{{details.image.url}}" alt="OnePlus 12" class="img-fluid image my-5 rounded-start">

    </div>
    <div class="col-12 col-lg-5 ms-4 mt-5 ">
        <div class="card-body">
            <p class="card-title  phone_name">{{details.name}}</p>
            <p class="card-text">{{details.detail}}</p>
            <p class="_PRICE ">stock:{{details.stock}}</p>
            <p class="card-text_PRICE fw-normal">₹{{details.price|add_commas}}</p>
            <p class="card-text pb-0 mb-0">Starting ₹5250/mo with 12-months No Cost EMI or
                ₹1760/mo <br>with Easy Upgrades 24-months No Cost EMI.
            </p>
            <p class="card-text pt-0 text-secondary">M.R.P. ₹{{details.price|add_commas}} (inclusive of all taxes)</p>
            <hr>
            <p class="card-text"><strong>Color:</strong> {{details.color}}</p>
            <p class="card-text mb-0 pb-3 " style="font-weight: 500;">ROM</p>
            <p class="mt-0 pt-0"><a class="btn btn-outline-dark rounded-0 me-1" href="#"
                    role="button">{{details.storage}}</a>
                <a class="btn btn-outline-dark rounded-0" href="">

                    16 GB RAM + 512 GB Storage</a>
            </p>
        </div>
    </div>
</div>
<div class="navbar fixed-bottom bg-light">
    {% if user.is_authenticated %}
    {% if details.stock != 0 %}
    <div class="container-fluid d-flex justify-content-end align-item-center">
        <a href="{% url 'Cart:addcart' details.id %}" type="button"
            class="btn  btn_addtocart rounded-0 text-light me-3">Add to cart </a>
        <a type="button" class="btn btn_buynow btn-secondary rounded-0  me-2">Buy now</a>
    </div>
    {% else %}
    <div class="container-fluid d-flex justify-content-center align-item-center">
        <p>
        <h2 class="stockout text-danger pb-3">Out of Stock</h2>
        </p>
    </div>

    </p>
</div>
{% endif %}
{% else %}
<div class="container-fluid d-flex justify-content-center align-item-center">
    <p>
    <h2 class="stockout text-danger pb-3">PleaseLogin</h2>
    {% endif %}


</div>
{% endblock %}


{% comment %}
{% if details.stock != 0 %}
<p>
    <a href="{% url 'cart_page:addcart' details.id %}" type="button" class="btn btn-warning">
        <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
            <path
                d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z" />
        </svg>&nbsp; Add to cart</a>

</p>
{% else %}
<p>
<h2 class="stockout text-danger">Out of Stock</h2>
</p>
{% endif %} {% endcomment %}

templates/error.html
<!DOCTYPE html>
<html>
<head>
    <title>Payment Error</title>
</head>
<body>
    <h1>Payment Error</h1>
    <p>There was an error processing your payment: {{ error.message }}</p>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title mb-4 text-center">Login</h2>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="Username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary w-100">Login</button>
                        </div>
                    </form>
                    {% if messages %}
                    <div class="alert alert-danger">
                        {% for message in messages %}
                        <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/products.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="main">
    <div class="container-fluid p-0">
        <div class="row  pt-5 ">
            {% for i in product %}
            <div class="col-xl-3 col-auto  card_col   mb-2">
                <a href="{% url 'Products:detail' i.id %}" class="text-decoration-none text-dark">
                    <div class="card card_product h-100 border-0 rounded-0  ">
                        <img class="image_product " src="{{i.image.url}}" width="310px" alt="">
                        <div class="card-body px-1">
                            <h5 class="card-title">{{i.name}}</h5>
                            <p class="text-danger p-0 m-0">6% OFF</p>
                            <p class="card-text">{{i.detail}}</p>
                            <a href="{% url 'Products:detail' i.id %}" class="btn btn-dark rounded-0 w-100">
                                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                                    <path fill="yellow"
                                        d="M440-600v-120H320v-80h120v-120h80v120h120v80H520v120h-80ZM280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM40-800v-80h131l170 360h280l156-280h91L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68.5-39t-1.5-79l54-98-144-304H40Z" />
                                </svg>
                                From ₹{{i.price|add_commas}}
                            </a>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    {% comment %} {% include './nav_footer/footer.html' %} {% endcomment %}
    {% endblock %}
  
  
      

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <!-- Profile Picture with Edit Form -->
        </div>
        <div class="col-md-8">
            <!-- User Information -->
            {% comment %} {% if profile.profilepic %} {% endcomment %}
            {% comment %} action="{% url 'User:profile' id=user.id %}" {% endcomment %}
            <form method="post" enctype="multipart/form-data" 
                id="profile-form">
                {% csrf_token %}

                <label for="profile-pic-upload" class="custom-file-upload">
                    {% if profile.profilepic %}
                    <img src="{{ profile.profilepic.url }}" height="100px" width="100px" alt="Profile Picture">
                    {% else %}
                    <img src="https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/profile-pic-male_4811a1.svg"
                        height="100px" width="100px" alt="Profile Picture">
                    {% endif %}
                    <i class="fa fa-pencil fa-lg text-primary"></i>
                    <input type="file" name="image" accept="image/*" required id="profile-pic-upload"
                        class="visually-hidden">
                </label>

            </form>
            <h2>User Profile</h2>
            <div class="mb-3">
                <strong>Name:</strong>{{ user.first_name }}
            </div>

            <div class="mb-3">
                <strong>Address:</strong>
            </div>
            <!-- Add more profile information here -->
        </div>
    </div>
</div>
{% if detail %}
{% for details in detail %}
as
<tr>
    <td>{{ details.phone }}</td><br>
    <td>{{ details.address }}</td><br>
    <td>{{ details.pincode }}</td><br>
    <td>{{ details.land_mark }}</td><br>
    <td>{{ details.city }}</td><br>
    <td>{{ details.state }}</td><br>
</tr>
{% endfor %}

{% else %}
<div class="container mt-5">
    <h2>User Details Form</h2>
    <form method="POST" action="{% url 'User:useradderess' profile.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="phone">USER id</label>
            <input type="number" class="form-control" name="user" value="{{user.id}}" placeholder="user" required>
        </div>
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone number" required>
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address" placeholder="Enter address" required>
        </div>
        <div class="form-group">
            <label for="pincode">Pincode</label>
            <input type="text" class="form-control" id="pincode" name="pincode" placeholder="Enter pincode" required>
        </div>
        <div class="form-group">
            <label for="landmark">Landmark</label>
            <input type="text" class="form-control" id="landmark" name="landmark" placeholder="Enter landmark">
        </div>
        <div class="form-group">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city" placeholder="Enter city" required>
        </div>
        <div class="form-group">
            <label for="state">State</label>
            <input type="text" class="form-control" id="state" name="state" placeholder="Enter state" required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endif %}


<script>
    // Automatically submit the form
    document.getElementById('profile-pic-upload').addEventListener('change', function () {
        document.getElementById('profile-form').submit();
    });
</script>

{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="main">

    <div class="container-fluid p-0">
        <div class="row mx-2  pt-5 ">
            {% if products %}
            {% for i in products %}
            <div class="col-xl-3 col-auto  card_col   mb-2">
                <a href="{% url 'Products:detail' i.id %}" class="text-decoration-none text-dark">

                    <div class="card card_product h-100 border-0 rounded-0  ">
                        <img class="image_product " src="{{i.image.url}}" width="310px" alt="">
                        <div class="card-body px-1">
                            <h5 class="card-title">{{i.name}}</h5>
                            <p class="text-danger p-0 m-0">6% OFF</p>
                            <p class="card-text">{{i.detail}}</p>
                            <a href="{% url 'Products:detail' i.id %}" class="btn btn-dark rounded-0 w-100">
                                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24">
                                    <path fill="yellow"
                                        d="M440-600v-120H320v-80h120v-120h80v120h120v80H520v120h-80ZM280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM40-800v-80h131l170 360h280l156-280h91L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68.5-39t-1.5-79l54-98-144-304H40Z" />
                                </svg>
                                From ₹{{i.price|add_commas}}
                            </a>
                        </div>
                    </div>
                </a>
            </div>
           
    {% endfor %}
    {% else %}
    <p>
        <h1 class="text-center pt-5 mt-5">No result found.</h1>
        </p>
    {% endif %}
        </div>
    </div>
    {% comment %} {% include './nav_footer/footer.html' %} {% endcomment %}
{% endblock %}
  
  
      